- name: Copy all required BIOS to Batocera BIOS folder
  copy:
    src: "{{ item }}"
    dest: "/media/corey/SHARE/bios/"
    mode: 0777
    owner: corey
    force: no
  with_fileglob:
    - "/media/corey/4649765178C51A81/Retrowarez/Bios/Bios/*"